routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('/app')->group(function(){
	Route::get('/', function(){
		return view('app');
	})->name('app');

	Route::get('/user', function(){
		return view('user');
	})->name('app.user');

	Route::get('/profile', function(){
		return view('profile');
	})->name('app.profile');


});
/*---------------------------------------*/

Route::post('/requeisicoes', function(Request $request) {
	return 'Hello POST';
    //
});

Route::get('produtos', function(){
	return view('produtos.index');
})->name('produtos');
Route::get('departamentos', function(){
	return view('departamentos.index');
})->name('departamentos');
Route::get('nome', 'MeuCotrolador@getNome');
Route::get('idade', 'MeuCotrolador@getIdade');
Route::get('multiplicar/{n1}/{n2}', 'MeuCotrolador@multiplicar');


Route::resource('clientes', 'ClienteControlador');

Route::get('opcoes/{opcao?}', function($opcao=null){
	return view('outros.opcoes', compact(['opcao']));
})->name('opcoes');

Route::get('bootstrap', function() {
    return view('outros.exemplo');
});

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Brand extends Model
{
    //
    use SoftDeletes;
    protected $fillable = ['name'];
}

app/Departament.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Departament extends Model
{
    //
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ClienteControlador.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ClienteControlador extends Controller
{
    private $clientes = [
        ['id'=>1, 'nome' => 'joao'],
        ['id'=>2, 'nome' => 'gabriel'],
        ['id'=>3, 'nome' => 'ana'],
        ['id'=>4, 'nome' => 'flavia'],
        
    ];

    public function __construct(){
        $clientes = session('clientes');
        if(!isset($clientes))
            session(['clientes' => $this->clientes]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clientes = session('clientes');
        $texte = "todos os clientes";
        return view('clientes.index', ['clientes'=>$clientes, 'titulo'=>$texte]);
        //return view('clientes.index')->with('clientes', $clientes);
        //return view('clientes.index', compact(['clientes']));
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clientes.create');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $clientes = session('clientes');
        $dados = ['id'=>end($clientes)['id']+1, 'nome'=> $request->nome];
        $clientes[] = $dados;
        session(['clientes'=>$clientes]);
        
        return redirect()->route('clientes.index');
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $clientes = session('clientes');
        $index = $this->getIndex($id, $clientes);
        $cliente = $clientes[$index];
        return view('clientes.info', compact(['cliente']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $clientes = session('clientes');
        $index = $this->getIndex($id, $clientes);
        $cliente = $clientes[$index];
        return view('clientes.edit', compact(['cliente']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $clientes = session('clientes');
        $index = $this->getIndex($id, $clientes);
        $clientes[$index]['nome'] = $request->nome;
        session(['clientes'=>$clientes]);
        
        return redirect()->route('clientes.index');
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $clientes = session('clientes');
        $index = $this->getIndex($id, $clientes);
        array_splice($clientes, $index, 1);
        session(['clientes'=>$clientes]);
        return redirect()->route('clientes.index');
    }

    private function getIndex($id, $clientes){
        $ids = array_column($clientes, 'id');
        $index = array_search($id, $ids);
        return $index;
    }
} 

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MeuCotrolador.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MeuCotrolador extends Controller
{
    //
    public function produtos(){
    	echo "<h1>Produtos</h1>";
    	echo "<ol>";
    	echo "<li>Notebook</li>";
    	echo "<li>Impressora</li>";
    	echo "<li>Mouse</li>";
    	echo "</ol>";
    	
    }

    public function getNome(){
    	return "joao gabriel";
    }

    public function getIdade(){
    	return "30";
    }

    public function multiplicar($n1, $n2){
    	return $n1 * $n2;
    }
}

resources/views/app.blade.php
<h1>App</h1>

<div>
	<a href="{{route('app.user')}}">user</a><br>
	<a href="{{route('app.profile')}}">Profile</a><br>
	<a href="{{route('app')}}">App</a><br>
</div>

resources/views/clientes/create.blade.php
@extends('layouts.principal')

@section('titulo', 'Cliente Novo')

@section('conteudo')

	<h3>Novo Cliente</h3>
	<form action="{{ route('clientes.store') }}" method="POST">
		@csrf
		<input type="text" name="nome">
		<input type="submit" name="salvar">
	</form>
@endsection

resources/views/clientes/edit.blade.php
@extends('layouts.principal')

@section('titulo', 'Cliente edit')

@section('conteudo')

	<h3>Editar Cliente</h3>
	<form action="{{ route('clientes.update', $cliente['id']) }}" method="POST">
		@csrf
		@method('PUT')
		<input type="text" name="nome" value="{{$cliente['nome']}}">
		<input type="submit" name="salvar">
	</form>
@endsection

resources/views/clientes/index.blade.php
@extends('layouts.principal')

@section('titulo', 'Cliente')

@section('conteudo')

<h3>{{$titulo}}</h3>
<a href="{{ route('clientes.create') }}">Novo Cliente</a>

	@if(count($clientes)>0)
		
		<ul>
			@foreach ($clientes as $c)
				{{-- expr --}}
				<li>
					{{ $c['id'] }}:{{ $c['nome'] }} ->
					<a href="{{ route('clientes.show', $c['id']) }}">Info</a>
					<a href="{{ route('clientes.edit', $c['id']) }}">Edit</a>
					<form action="{{ route('clientes.destroy', $c['id']) }}" method="POST">
						@csrf
						@method('DELETE')
						<input type="submit" name="Apagar" value="Apagar">
					</form>
				</li>
				{{-- {{var_dump($loop)}} --}}
			@endforeach
		</ul>
	@else
		<h4>não existe usuários cadastrados</h4>
	@endif

@endsection

resources/views/clientes/info.blade.php
@extends('layouts.principal')

@section('titulo', 'Cliente Detalhe')

@section('conteudo')

	<h3>Informações do cliente</h3>

	<p>ID: {{$cliente['id']}}</p>
	<p>NOME: {{$cliente['nome']}}</p>

	<br>
	<a href="{{route('clientes.index')}}">Voltar</a>
@endsection

resources/views/departamentos/index.blade.php
@extends('layouts.principal')

@section('titulo', 'departamentos')

@section('conteudo')

	<h3>Departamentos</h3>

	<ul>
		<li>computadores</li>
		<li>eletronicos</li>
		<li>acessorios</li>
		<li>roupas</li>
	</ul>

	@alerta( ['titulo'=>'erro fatal', 'tipo'=>'info'])
		<p><strong>Erro Inesperado</strong></p>
		<p>ocorreu um erro inesperado</p>
	@endalerta
	@alerta( ['titulo'=>'erro fatal', 'tipo'=>'error'])
		<p><strong>Erro Inesperado</strong></p>
		<p>ocorreu um erro inesperado</p>
	@endalerta
	@alerta( ['titulo'=>'erro fatal', 'tipo'=>'success'])
		<p><strong>Erro Inesperado</strong></p>
		<p>ocorreu um erro inesperado</p>
	@endalerta
	@alerta( ['titulo'=>'erro fatal', 'tipo'=>'warning'])
		<p><strong>Erro Inesperado</strong></p>
		<p>ocorreu um erro inesperado</p>
	@endalerta
	
	
@endsection

resources/views/layouts/bootstrap.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="csrf-token" content="{{csrf_token()}}">
    
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Pricing example · Bootstrap</title>

    

    <!-- Bootstrap core CSS -->
<link href="{{asset('css/app.css')}}" rel="stylesheet">

    <!-- Favicons -->
<!-- <link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c"> -->


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{asset('css/pricing.css')}}" rel="stylesheet">
  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Company name</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="#">Features</a>
    <a class="p-2 text-dark" href="#">Enterprise</a>
    <a class="p-2 text-dark" href="#">Support</a>
    <a class="p-2 text-dark" href="#">Pricing</a>
  </nav>
  <a class="btn btn-outline-primary" href="#">Sign up</a>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Pricing</h1>
  <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
</div>

<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Free</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>10 users included</li>
          <li>2 GB of storage</li>
          <li>Email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Pro</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>20 users included</li>
          <li>10 GB of storage</li>
          <li>Priority email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Get started</button>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Enterprise</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>30 users included</li>
          <li>15 GB of storage</li>
          <li>Phone and email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>
      </div>
    </div>
  </div>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="{{asset('img/bootstrap-solid.svg')}}" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">&copy; 2017-2019</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Cool stuff</a></li>
          <li><a class="text-muted" href="#">Random feature</a></li>
          <li><a class="text-muted" href="#">Team feature</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
          <li><a class="text-muted" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource name</a></li>
          <li><a class="text-muted" href="#">Another resource</a></li>
          <li><a class="text-muted" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>
<script src="{{asset('js/app.js')}}" type="text/javascript"></script>
</body>
</html>

resources/views/layouts/principal.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-auto, initia-scale=1">
	<title>@yield('titulo')</title>
	<link rel="stylesheet" type="text/css" href="{{ asset('css/principal.css') }}">
</head>
<body>
	<div class="row">
		<div class="col1">
			<div class="menu">
				<ul>
					<li><a class="{{request()->routeIs('clientes.*') ? 'active': ''}}" 
						href="{{ route('clientes.index') }}">Clientes</a></li>
					<li><a class="{{request()->routeIs('produtos') ? 'active': ''}}"
						href="{{ route('produtos') }}">Produto</a></li>
					<li><a class="{{request()->routeIs('departamentos') ? 'active': ''}}"
						href="{{ route('departamentos') }}">Departamento</a></li>
					<li><a class="{{request()->routeIs('opcoes') ? 'active': ''}}"
						href="{{ route('opcoes') }}">Opções</a></li>
						
				</ul>
			</div>
		</div>
		<div class="col2">
			@yield('conteudo')
			
		</div>
	</div>
</body>
</html>

resources/views/outros/exemplo.blade.php
@extends('layouts.bootstrap')

@section('conteudo')
@endsection

resources/views/outros/opcoes.blade.php
@extends('layouts.principal')

@section('titulo', 'opcoes')

@section('conteudo')

	<div class="options">
		<ul>
			<li><a class="warning" href="{{ route('opcoes',1) }}">warning</a></li>
			<li><a class="info"    href="{{ route('opcoes',2) }}">info</a></li>
			<li><a class="success" href="{{ route('opcoes',3) }}">success</a></li>
			<li><a class="error"   href="{{ route('opcoes',4) }}">error</a></li>
		</ul>
</div>

@if (isset($opcao))

	@switch($opcao)
	    @case(1)	        
			@alerta( ['titulo'=>'erro fatal', 'tipo'=>'warning'])
				<p><strong>Warning</strong></p>
				<p>ocorreu um erro inesperado</p>
			@endalerta
	        @break
		@case(2)	        
			@alerta( ['titulo'=>'erro fatal', 'tipo'=>'info'])
				<p><strong>Info</strong></p>
				<p>ocorreu um erro inesperado</p>
			@endalerta
	        @break
		@case(3)	        
			@alerta( ['titulo'=>'erro fatal', 'tipo'=>'success'])
				<p><strong>Success</strong></p>
				<p>ocorreu um erro inesperado</p>
			@endalerta
	        @break
		@case(4)	        
			@alerta( ['titulo'=>'erro fatal', 'tipo'=>'error'])
				<p><strong>Error</strong></p>
				<p>ocorreu um erro inesperado</p>
			@endalerta
	        @break
		
	    {{-- @default
	            Default case... --}}
	@endswitch


	{{-- expr --}}
@endif

@endsection

resources/views/produtos/index.blade.php
@extends('layouts.principal')

@section('titulo', 'produtos')

@section('conteudo')

	<h3>produtos</h3>

	<ul>
		<li>PC</li>
		<li>Notebooks</li>
		<li>Mouse</li>
		<li>camiseta polo</li>
	</ul>
	
@endsection

resources/views/profile.blade.php
<h1>Profile</h1>

<div>
	<a href="{{route('app.user')}}">user</a><br>
	<a href="{{route('app.profile')}}">Profile</a><br>
	<a href="{{route('app')}}">App</a><br>
</div>

resources/views/user.blade.php
<h1>User</h1>

<div>
	<a href="{{route('app.user')}}">user</a><br>
	<a href="{{route('app.profile')}}">Profile</a><br>
	<a href="{{route('app')}}">App</a><br>
</div>